name: Release Workflow

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  test:
    uses: ./.github/workflows/testing.yaml

  release:
    name: Release Application
    needs: test
    runs-on: macOS-latest
    env:
      JAVA_TOOL_OPTIONS: -Xmx4g -XX:+UseParallelGC
      ENABLE_APP_VERSIONING: false

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 18
          cache: gradle

      - name: Decode Keystore
        env:
          ENCODED_STRING: ${{ secrets.RELEASE_KEYSTORE }}
          KEY_STORE_PATH: ${{ secrets.KEY_STORE_PATH }}

        run: |
          echo $ENCODED_STRING > keystore-b64.txt
          base64 -d keystore-b64.txt > $KEY_STORE_PATH

      #2
      - name: Build Release apk
        env:
          SIGNING_KEY_STORE_PATH: ${{ secrets.KEY_STORE_PATH }}
          SIGNING_KEY_ALIAS: ${{ secrets.ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
        run: ./gradlew assembleRelease

      - name: Build Release bundle
        env:
          SIGNING_KEY_STORE_PATH: ${{ secrets.KEY_STORE_PATH }}
          SIGNING_KEY_ALIAS: ${{ secrets.ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
        run: ./gradlew bundleRelease

      - name: Hole die builds Heim ins Reich
        run: |
          mv ../build ./app/

      #3
      - name: Upload Release Build to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release-artifacts
          path: |
            ${{ github.workspace }}/app/build/app/outputs/apk/release/
            ${{ github.workspace }}/app/build/app/outputs/bundle/release/
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`

      #4
      - name: Create Github Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          prerelease: false
          files: |
            ${{ github.workspace }}/app/build/app/outputs/apk/release/app-release.apk
            ${{ github.workspace }}/app/build/app/outputs/bundle/release/app-release.aab

      - name: Deploy to Google Playstore
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ SERVICE_ACCOUNT_JSON }}
          packageName: de.byte_artist.quickmemoplus
          releaseFiles: ${{ github.workspace }}/app/build/outputs/bundle/release/app-release.aab, ${{ github.workspace }}/app/build/outputs/apk/release/app-release.apk
          track: production
          status: completed
          inAppUpdatePriority: 2
          userFraction: 0.33
          whatsNewDirectory: distribution/whatsnew
          mappingFile: ${{ github.workspace }}/app/build/outputs/mapping/release/mapping.txt
          debugSymbols: ${{ github.workspace }}/app/intermediates/merged_native_libs/release/out/lib
