name: Testing Workflow

on:
  pull_request:
    branches:
      - develop
      - master

#env:
#  ANDROID_HOME: "/Users/runner/Library/android-sdk"
#  ANDROID_SDK_TOOLS: "7583922_latest"

jobs:
#  testing:

#    runs-on: macOS-latest
#    timeout-minutes: 25
#    env:
#      JAVA_TOOL_OPTIONS: -Xmx4g -XX:+UseParallelGC
#      ENABLE_APP_VERSIONING: false

#    runs-on: macos-latest

  test:
    name: Lint Check and Testing
    runs-on: ubuntu-latest

    strategy:
      matrix:
        api-level: [24, 28, 29, 30, 34]
    #        target: [default, google_apis]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Checkout
        uses: actions/checkout@v1

      - name: Run Android Linter
        run: ./gradlew lintRelease

      - name: Upload Linter results
        uses: actions/upload-artifact@v1
        with:
          name: linter-results
          path: app/build/reports/lint-results-release.html

      - name: Run all checks
        run: ./gradlew check

      - name: Run Unit Tests
        run: ./gradlew test

      - name: Run Tests
        run: bash ./gradlew test --stacktrace

      - name: Add Android SDK to path
        run: |
          echo "ANDROID_SDK_ROOT=$ANDROID_HOME" >> $GITHUB_ENV
          echo "$ANDROID_HOME/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$ANDROID_HOME/platform-tools" >> $GITHUB_PATH

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-${{ github.job }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}
          restore-keys: |
            ${{ runner.os }}-${{ github.job }}-

      - uses: actions/cache@v2
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd

      - name: Run Android instrumented tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
#          arch: x86
#          profile: Nexus 5X
#          force-avd-creation: false
#          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
#          emulator-build: 6609375
          script: ./gradlew connectedAndroidTest --stacktrace

      - name: Upload Unit tests results
        uses: actions/upload-artifact@v1
        with:
          name: unit-tests-results
          path: app/build/reports/lint-results-release.html
