name: Testing Workflow

on:
  pull_request:
    branches:
      - develop
      - master

jobs:

  test:
    name: Lint Check and Testing
    runs-on: macOS-latest
    env:
      JAVA_TOOL_OPTIONS: -Xmx4g -XX:+UseParallelGC
      ENABLE_APP_VERSIONING: false

    strategy:
      matrix:
        api-level: [24, 28, 29, 30, 31, 34]
        arch: [x86, x86_64]
        target: [google_apis]
        exclude:
          - api-level: 30
            arch: x86
          - api-level: 31
            arch: x86
          - api-level: 34
            arch: x86
#            target: [default, google_apis]

    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 18
          cache: gradle

      - name: Android lint
        run: ./gradlew lintRelease

      - uses: yutailang0119/action-android-lint@v3
        with:
          report-path: build/reports/*.xml # Support glob patterns by https://www.npmjs.com/package/@actions/glob
        continue-on-error: false # If annotations contain error of severity, action-android-lint exit 1.

      - name: Upload Linter results
        uses: actions/upload-artifact@v1
        with:
          name: linter-results
          path: ../build/app/reports/lint-results-release.html

      - name: Run all checks
        run: ./gradlew check

      - name: Run Tests
        run: bash ./gradlew test

      - name: Run Android instrumented tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: ${{ matrix.arch }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          script: ./gradlew connectedAndroidTest


###########################################################################################################

  release:
    name: Release Application
#    needs: test
    runs-on: macOS-latest
    env:
      JAVA_TOOL_OPTIONS: -Xmx4g -XX:+UseParallelGC
      ENABLE_APP_VERSIONING: false

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 18
          cache: gradle

      - name: Decode Keystore
        env:
          ENCODED_STRING: ${{ secrets.RELEASE_KEYSTORE }}
          KEY_STORE_PATH: ${{ secrets.KEY_STORE_PATH }}

        run: |
          echo $ENCODED_STRING > keystore-b64.txt
          base64 -d keystore-b64.txt > $KEY_STORE_PATH
          
      #2
      - name: Build Release apk
        env:
          SIGNING_KEY_STORE_PATH: ${{ secrets.KEY_STORE_PATH }}
          SIGNING_KEY_ALIAS: ${{ secrets.ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
        run: ./gradlew assembleRelease

      - name: Build Release bundle
        env:
          SIGNING_KEY_STORE_PATH: ${{ secrets.KEY_STORE_PATH }}
          SIGNING_KEY_ALIAS: ${{ secrets.ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
        run: ./gradlew bundleRelease

      - name: debug current folder structure
        run: |
          ls -lisa ../
          ls -lisa ./
          ls -lisa app/

      - name: Hole die builds Heim ins Reich
        run: |
          mv ../build ./app/

      - name: debug current folder structure
        run: |
          ls -lisa ./
          ls -lisa app/
          ls -lisa app/build/
          ls -lisa app/build/app/
          ls -lisa app/build/app/outputs/
          ls -lisa app/build/app/outputs/apk/

      #3
      - name: Upload Release Build to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release-artifacts
          path: |
            apk/release/
            bundle/release/

      #4
      - name: Create Github Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          prerelease: true
          files: |
            build/app/outputs/apk/release/app-release.apk
            build/app/outputs/bundle/release/app-release.aab